name: amazone
description: A new Bacu project.

publish_to: 'none' 

version: 1.0.4+4

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.17
  connectivity_plus: ^3.0.4
  flutter_inappwebview: ^5.7.2+3
  url_launcher: ^6.1.8
  store_redirect: ^2.0.1
  cupertino_icons: ^1.0.2
  advertising_id: ^2.4.0
  device_info_plus: ^8.2.0
  animate_do: ^3.0.2
  flutter_native_splash: ^2.2.19
  change_app_package_name: ^1.1.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios:
  image_path: "assets/images/B_1.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:  
  color: "#FFFFFF"
  andriod: true
  ios: true
  andriod_gravity: centre
  fullscreen: true
  ios_content_mode: scaleAspectFill
  web: false

flutter:

 
  uses-material-design: true

  assets:
    - assets/images/
